name: Push to PyPI

on:
  push:
    branches:
      - main

jobs:

  sdist:
    name: Create Source Distribution
    runs-on: ubuntu-latest
    steps:
      - name: Create Source Distribution
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine
          mkdir -p build
          python3 setup.py sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  build-and-test-wheels:
    name: Wheel
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.10", "3.11", "3.12"]
    steps:
      - uses: compas-dev/compas-actions.build@v4
        with:
          invoke_lint: true
          use_conda: true
          check_import: true
          python: ${{ matrix.python }}

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}-${{ matrix.python }}
          path: compas_cgal-*.whl

  upload:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    needs: [sdist, build-and-test-wheels]
    steps:
      - uses: actions/download-artifact@v4

      - name: Select wheels to push
        run : |
          mkdir dist
          cp -r *.whl dist/
          ls dist

      - name: upload to PyPI
        if: github.event_name == 'push' && github.ref_name == 'main'
        env:
          TWINE_USERNAME: ...
          TWINE_PASSWORD: ...
        run: |
          pip install  twine
          python3 -m twine upload --verbose dist/*
