on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python: ['3.8', '3.9', '3.10']

    steps:
      - uses: compas-dev/compas-actions.build@v2
        with:
          test_lint: true
          test_compas: true
          use_conda: true
          python: ${{ matrix.python }}

  Publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: compas-dev/compas-actions.publish@v2
        with:
          pypi_token: ${{ secrets.PYPI }}
          github_token: ${{ secrets.GITHUB_TOKEN }}